# Resolving clustering problems

In [236]:
%run Feature_Extractions.ipynb
%run MyKmeans.ipynb
%run Utils.ipynb
import numpy as np

1.12.0
1.12.0


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Deea\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Deea\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


## For negative vs postive sentiment

Extracting the data from the file

In [237]:
inputs,outputs,dataNames,labelNames=load_data('data/reviews_mixed.csv')
print(dataNames)
print(labelNames)
print(inputs[:5])
print(outputs[:5])

['Text', 'Sentiment']
['positive', 'negative']
['The rooms are extremely small, practically only a bed.', 'Room safe did not work.', 'Mattress very comfortable.', 'Very uncomfortable, thin mattress, with plastic cover that rustles every time you move.', 'No bathroom in room']
['negative', 'negative', 'positive', 'negative', 'negative']


Extracting training inputs,outputs,test inputs and outputs

In [238]:
trainInputs,trainOutputs,testInputs,testOutputs=split_data(inputs,outputs,0.8)
print(trainInputs[:5])
print(trainOutputs[:5])
print(testInputs[:5])
print(testOutputs[:5])

['still easy to reach.', 'Some thinks didnt work well : air, tv , open windows,', 'Room was not cleaned even once during our stay.', 'The bed is really terrible,especially the blanket is heavy and terrible terrible quality.', 'The TV was not working.']
['positive', 'negative', 'negative', 'negative', 'negative']
['The rooms are extremely small, practically only a bed.', 'Mattress very comfortable.', 'The bed was soooo comfy.', 'The bed is very comfortable.', 'Very spacious rooms, quiet and very comfortable.']
['negative', 'positive', 'positive', 'positive', 'positive']


Get Train Features BOW

In [239]:
trainFeatures=get_bow(trainInputs)

Get Train Vocabulary

In [240]:
vocab=get_vocabulary(trainInputs)


Get Test Bow

In [241]:
testFeatures=get_bow(testInputs)

Get Train Vocabulary

In [242]:
testVocab=get_vocabulary(testInputs)

In [243]:
print("Voabulary Size:",len(trainFeatures[0]))
print(np.array(trainFeatures[:1]))
print(np.array(testFeatures[:1]))
print("Train Data Size:",len(trainFeatures))
print("Test Data Size:",len(testFeatures))
print("Train Features Size:",len(trainFeatures[0]))
print("Some words in the vocabulary:",vocab[0:10])

Voabulary Size: 470
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0]]
[[0 0 0 0 

# Other characteristics

In [244]:
#print(trainInputs)
sentiments,model_trained_sentient=get_sentiments(trainInputs)

In [245]:
show_sentiments(sentiments[:5],trainInputs[:5])

Document text:still easy to reach.
Overall sentiment:positive
Document text:Some thinks didnt work well : air, tv , open windows,
Overall sentiment:negative
Document text:Room was not cleaned even once during our stay.
Overall sentiment:negative
Document text:The bed is really terrible,especially the blanket is heavy and terrible terrible quality.
Overall sentiment:negative
Document text:The TV was not working.
Overall sentiment:negative


# Tagging emotions using KMeans

In [263]:
kmeans=get_KMeansSklearn(n_clusters=2,randomstates=0)

In [264]:
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score


In [265]:
def evaluate_clusters(cluster_labels, true_labels):
    conf_matrix = confusion_matrix(true_labels, cluster_labels)
    acc = accuracy_score(true_labels, cluster_labels)
    print(f"Confusion Matrix:\n{conf_matrix}\nAccuracy: {acc}")

In [268]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

train_features = vectorizer.fit_transform(trainInputs).toarray()
test_features = vectorizer.transform(testInputs).toarray()

kmeans.fit(train_features)

# Assign clusters to test data
test_labels = kmeans.predict(test_features)

test_inertia = sum(np.linalg.norm(np.array(x) - kmeans.cluster_centers_[c_idx])**2 for x, c_idx in zip(test_features, test_labels))
print(test_inertia)
testValOutputs = [1 if x == "positive" else 0 for x in testOutputs]
print(testValOutputs)
print(test_labels)
evaluate_model(test_labels,testValOutputs)
toPred=["By choosing a bike over a car, I’m reducing my environmental footprint. Cycling promotes eco-friendly transportation, and I’m proud to be part of that movement.."]
prediction=kmeans.predict(vectorizer.transform(toPred).toarray())
if prediction[0]==0:
    print("Negative")
else:
    print("Positive")



40.01143751669931
[0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0]
[1 0 1 1 1 1 1 0 0 0 0 1 1 1 0 1 1 1 0 1 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 1
 0 0 1 1 1]
Confusion Matrix:
[[ 9 16]
 [ 9  8]]
Accuracy: 0.40476190476190477
Negative


# My own Kmeans

In [275]:
from collections import Counter


def train_and_map(trainInputs, trainOutputs, testInputs, testOutputs, nClusters=2, max_iter=10000):
    vectorizer = TfidfVectorizer()
    trainFeatures = vectorizer.fit_transform(trainInputs).toarray()

    model = MyKmeans(nClusters, max_iter)
    model.fit(trainFeatures, trainOutputs)
    testFeatures = vectorizer.transform(testInputs).toarray()

    train_labels = model.predict(testFeatures)

    evaluate_clusters(train_labels, testOutputs)

    # Compute cluster sentiment mapping
    cluster_sentiment_map = {}
    for i in range(nClusters):
        cluster_labels = np.array(trainOutputs)[train_labels == i]
        counts = Counter(cluster_labels)
        cluster_sentiment_map[i] = "positive" if counts["positive"] > counts["negative"] else "negative"

    return model, vectorizer, cluster_sentiment_map

In [276]:
def predict_sentiment(model, vectorizer, text):
    new_features = vectorizer.transform(text).toarray()
    new_cluster_labels = model.predict(new_features)

    predicted_sentiments = new_cluster_labels
    return predicted_sentiments

In [277]:
model, vectorizer, cluster_sentiment_map = train_and_map(trainInputs, trainOutputs, testInputs, testOutputs)
new_text = ["By choosing a bike over a car, I’m reducing my environmental footprint. Cycling promotes eco-friendly transportation, and I’m proud to be part of that movement.."]
predicted_sentiment = predict_sentiment(model, vectorizer, new_text)
print(f"Predicted Sentiment: {predicted_sentiment}")

Confusion Matrix:
[[25  0]
 [17  0]]
Accuracy: 0.5952380952380952
Predicted Sentiment: ['negative']


In [316]:
sent,model=get_sentiments(new_text)
print(sent)
show_sentiments(sent,new_text)

[AnalyzeSentimentResult(id=0, sentiment=positive, warnings=[], statistics=None, confidence_scores=SentimentConfidenceScores(positive=0.94, neutral=0.05, negative=0.01), sentences=[SentenceSentiment(text=By choosing a bike over a car, I’m reducing my environmental footprint. , sentiment=neutral, confidence_scores=SentimentConfidenceScores(positive=0.01, neutral=0.98, negative=0.01), length=72, offset=0, mined_opinions=[]), SentenceSentiment(text=Cycling promotes eco-friendly transportation, and I’m proud to be part of that movement.., sentiment=positive, confidence_scores=SentimentConfidenceScores(positive=0.94, neutral=0.05, negative=0.01), length=89, offset=72, mined_opinions=[])], is_error=False)]
Document text:By choosing a bike over a car, I’m reducing my environmental footprint. Cycling promotes eco-friendly transportation, and I’m proud to be part of that movement..
Overall sentiment:positive


# DBSCAN - apparently NOT suitable for this problem at all
## it identifies the noise points and the clusters
## everything is noise in this case

In [296]:
from sklearn.cluster import DBSCAN

In [314]:
vectorizer = TfidfVectorizer()
train_features = vectorizer.fit_transform(trainInputs).toarray()
# Aplicarea DBSCAN
dbscan = DBSCAN(eps=0.9, min_samples=2)  # Parametrii EPS și min_samples pot fi ajustați
cluster_labels = dbscan.fit_predict(train_features)
for i in set(cluster_labels):
    cluster_points = np.array(trainOutputs)[cluster_labels == i]
    counts = Counter(cluster_points)

    if counts:
        cluster_sentiment_map[i] = "positive" if counts["positive"] > counts["negative"] else "negative"

print(cluster_labels)
# Evaluarea clusterelor
evaluate_clusters([cluster_sentiment_map.get(l, "unknown") for l in cluster_labels],trainOutputs)
test_features = vectorizer.transform(testInputs).toarray()
test_cluster_labels = dbscan.fit_predict(test_features)
test_predicted_sentiments = [cluster_sentiment_map.get(l, "unknown") for l in  test_cluster_labels]
evaluate_clusters(test_predicted_sentiments, testOutputs)
print(dbscan.fit_predict(vectorizer.transform(["By choosing a bike over a car, I’m reducing my environmental footprint. Cycling promotes eco-friendly transportation, and I’m proud to be part of that movement.."]).toarray()))

[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
Confusion Matrix:
[[117   0]
 [ 48   0]]
Accuracy: 0.7090909090909091
Confusion Matrix:
[[24  0  1]
 [16  0  1]
 [ 0  0  0]]
Accuracy: 0.5714285714285714
[-1]


## GMM - Gaussian Mixture Model
## let's see how it performs

In [315]:
from sklearn.mixture import GaussianMixture

vectorizer = TfidfVectorizer()
train_features = vectorizer.fit_transform(trainInputs).toarray()
# Applying GMM
n_clusters = 2  #  avem pozitiv și negativ
gmm = GaussianMixture(n_components=n_clusters, random_state=20)
gmm.fit(train_features)
cluster_labels = gmm.predict(train_features)
# print(cluster_labels)

# print(cluster_labels)
cluster_sentiment_map = {}
# Evaluarea clusterelor
cluster_sentiment_map = {}
for i in set(cluster_labels):
    cluster_points = np.array(trainOutputs)[cluster_labels == i]
    counts = Counter(cluster_points)

    if counts:
        cluster_sentiment_map[i] = "positive" if counts["positive"] > counts["negative"] else "negative"
predicted_sentiments = [cluster_sentiment_map.get(l, "unknown") for l in cluster_labels]
evaluate_clusters(predicted_sentiments, trainOutputs)

    # Testing
test_features = vectorizer.transform(testInputs).toarray()
test_cluster_labels = gmm.predict(test_features)
test_predicted_sentiments = [cluster_sentiment_map.get(l, "unknown") for l in test_cluster_labels]
evaluate_clusters(test_predicted_sentiments,testOutputs)
print(gmm.predict(vectorizer.transform(["By choosing a bike over a car, I’m reducing my environmental footprint. Cycling promotes eco-friendly transportation, and I’m proud to be part of that movement.."]).toarray()))


Confusion Matrix:
[[117   0]
 [ 48   0]]
Accuracy: 0.7090909090909091
Confusion Matrix:
[[25  0]
 [17  0]]
Accuracy: 0.5952380952380952
[0]
